language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - cd ..
  - git clone https://github.com/catalyst-cooperative/pudl.git
  - cd pudl
  - pip install -e .
  - cd ../PowerGenome
# command to run tests
script:
  - pytest
